namespace OnlineLearningPlatform.Application.Services.AiQuiz;

public class MockAiQuizGenerator : IAiQuizGenerator
{
    public Task<List<GeneratedQuestion>> GenerateMcqAsync(string lessonText, int count)
    {
        // Super simple mock: creates generic MCQs based on lesson keywords
        var topic = string.IsNullOrWhiteSpace(lessonText)
            ? "this lesson"
            : (lessonText.Length > 40 ? lessonText[..40] + "..." : lessonText);

        var list = new List<GeneratedQuestion>();

        for (int i = 1; i <= count; i++)
        {
            list.Add(new GeneratedQuestion
            {
                QuestionText = $"Q{i}: Which statement best matches {topic}?",
                Explanation = "Generated by mock AI. Instructor should edit.",
                Options = new()
                {
                    new() { AnswerText = "Option A", IsCorrect = false },
                    new() { AnswerText = "Option B", IsCorrect = true  },
                    new() { AnswerText = "Option C", IsCorrect = false },
                    new() { AnswerText = "Option D", IsCorrect = false },
                }
            });
        }

        return Task.FromResult(list);
    }
}
